### ISSUE TITLE
Credentials not working after migration from legacy selfhosted server

### ISSUE THREAD

**Issue by LendingMemo** [standardnotes/standalone#12]
Hi StandardNotes,

I migrated my database and got the new repo cloned and started up. But when I try to log in via my app on iOS, a box pops up and it says my credentials are wrong. I double checked that the username and password are the same. Is there anything I'm doing wrong on my end?

**Comment by LendingMemo** [comment]
I'm curious if this is an issue of dumping the MySQL db from the legacy syncing-server incorrectly. The file dump seemed to work fine, and I imported it into the `import` folder, but maybe I screwed something up on the backend.

**Comment by mobitar** [comment]
Hard to say without more info/logs. You could also try a client-side import instead. That is, download a backup of your account data using the SN app, then import it into a new account using the new server.

**Comment by PhoneMechanic** [comment]
Did you check your database and see if your data imported?

**Comment by mwmason** [comment]
Hi,

I've been working on migrating my legacy server to node-js and I've exported my mysql db and placed the dump file in the data/import directory.  However, when I start the service, while I do see empty tables created in my new db target, I do not see my data imported.  Is there some function or specific call to initiate the import?

I was successful in importing from an SN backup as suggested by @mobitar - but if there are multiple users (not my case) that wouldn't work too easily.

Thank you!

From  [https://docs.standardnotes.org/self-hosting/legacy-migration/#importing-your-database-dump](url)
`In order to import your data to the database that our Standalone setup will create, just place your dbdump.sql file inside the path-to-your-standalone/data/import folder. The data will be imported once the setups starts.`

**Comment by joekerna** [comment]
were you able to fix this? I'm experiencing the same issue. I've updated from legacy to standalone and I get `Invalid email or password`
