### ISSUE TITLE
Cannot POST error when signing in

### ISSUE THREAD

**Issue by stevensiebe** [standardnotes/standalone#71]
After registering an account and specifying my custom sync server, I'm signed into an active session. I can create and edit notes normally. However when trying to sign out and back in, I see the error:
```
<!DOCTYPE html> <html lang="en" <head> 
<meta charset="utf-8"> <title>Error</title> 
</head> <body> <pre>Cannot POST /v2/login-
params</pre> </body> </html>
```
healthcheck reports OK, and granting a subscription to my user in the database works for that session.

**Comment by reanim8ed** [comment]
I have experienced the same problem.
Was setting up fresh setup on new server, all containers started, healthcheck reports OK, last record in logs shows: 
`api-gateway_1 | {"message":"Server started on port 3000","level":"info"}` 
If I access URL directly, I get: Welcome to the Standard Notes server infrastructure. Everything looks like it should be good.

But if I try to use it as custom sync server, the POST request to `/v2/login-params`gets 404 error.

**Comment by sleepy-soul** [comment]
Hey, I am also having same issue in my clean install. Healthcheck looks OK. 
I am using Traefik reverse proxy and checked it as well. Couldn't find any errors there as well

I was able to register user, but `PAYMENTS_SERVER_URL` was missing in my `api-gateway.env` Later I added it to point to my api-gateway:3000 and errors shows was gone, but now if I try to register user, it says an existing registration is already in process and when logging to existing user, gives me above error. `Cannot POST /v2/login-
params`

**Comment by handcraftedbits** [comment]
I had this issue too.  [This commit](https://github.com/standardnotes/snjs/commit/1bc19b79decf83a563d1cf095ee2e56f738152d1) introduced `/v2/login-params` and it requires newer versions of some of the containers in order to pick up the change.  As you can see [here](https://github.com/standardnotes/snjs/commit/1bc19b79decf83a563d1cf095ee2e56f738152d1#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3R62), `docker-compose.yml` was changed in the `snjs` project but not in the `standalone` project, which is what most of us use.

So, simple fix:

* `./server.sh stop`
* Edit `docker-compose.yml`, update:
  * `image: standardnotes/syncing-server-js:1.52.0` -> `image: standardnotes/syncing-server-js:1.52.1`
  * `image: standardnotes/api-gateway:1.37.0` -> `image: standardnotes/api-gateway:1.38.0`
  * `image: standardnotes/auth:1.43.0` -> `image: standardnotes/auth:1.45.0`
 * `./server.sh start`

Worked for me.
